Add Python 2.6 to matrix tests
Not adding Python 3.3 because import behaviour has changed:
```
Traceback (most recent call last):
  File "/Users/dcarley/projects/govuk/collectd_cdn_stats/.tox/py33/lib/python3.3/site-packages/nose/case.py", line 382, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/Users/dcarley/projects/govuk/collectd_cdn_stats/.tox/py33/lib/python3.3/site-packages/nose/util.py", line 469, in try_run
    return func()
  File "/Users/dcarley/projects/govuk/collectd_cdn_stats/test/unit/test_fastly.py", line 13, in setup
    from collectd_cdn import fastly
ImportError: cannot import name fastly
```